[package]
name = "hitomezashi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.1"
nannou_egui = "0.5.0"
rand_pcg = "0.3.1"
rand_seeder = "0.2.3"
