[package]
name = "hitomezashi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.19.0"
nannou_egui = "0.19.0"
rfd = "0.14.0"
png = "0.17.0"
serde_json = "1.0"
image = "0.24.0"
